name: uc-python-dl
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - pip>=20.3
    - numpy=1.19
    - pandas=1.2
    - seaborn=0.11
    - ipykernel>=5.3
    - scikit-learn=0.24
    - plotnine=0.7
