name: uc-python
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - pip>=20.3
    - numpy=1.19
    - keras>=2.4
    - fuzzywuzzy>=0.18
    - gensim>=3.8
    - pandas=1.2
    - seaborn=0.11
    - ipykernel>=5.3
