name: uc-python
channels:
    - defaults
    - conda-forge
dependencies:
    - category_encoders>=2.2.2
    - ipykernel>=5.3
    - matplotlib>=3.3.4
    - missingno=0.4.2
    - mlflow=1.22
    - numpy=1.19
    - pandas=1.2
    - pip>=20.3
    - plotnine=0.7
    - python=3.8
    - scikit-learn=0.24
    - seaborn=0.11
